[project]
name = "ebanking-agent"
version = "0.1.0"
description = "Demo Banking Agent with MCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.0",
    "fastmcp>=2.11.3",
    "mistralai>=1.9.11",
]
